import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    // Build output anywhere (esp. the minified chrome-extension/dist bundle)
    // — lint real source, not generated artifacts. This is what made
    // `pnpm lint` report hundreds of warnings on bundled JS.
    '**/dist/**',
    'chrome-extension/dist/**',
    'next-env.d.ts',
    'supabase/**',
    // Auto-generated by Supabase CLI — @ts-nocheck is intentional
    'src/types/database.ts',
    // WR-13 (review 2026-08-11): `.claude/worktrees/**` holds live agent
    // worktrees, each a FULL gitignored duplicate of this repo. Without this
    // ignore, `pnpm lint` picks up the duplicate src/types/database.ts and
    // exits non-zero with `error Do not use "@ts-nocheck"` — so the gate
    // CLAUDE.md mandates ("pnpm lint passes") only passed when no worktree
    // happened to exist. Same reasoning as vitest.config.ts's `.claude/**`
    // exclude, which is already there for exactly this: the gate must
    // describe THIS tree only.
    '.claude/**',
  ]),
])

export default eslintConfig
