import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    // Build output anywhere (esp. the minified chrome-extension/dist bundle)
    // — lint real source, not generated artifacts. This is what made
    // `pnpm lint` report hundreds of warnings on bundled JS.
    '**/dist/**',
    'chrome-extension/dist/**',
    'next-env.d.ts',
    'supabase/**',
    // Auto-generated by Supabase CLI — @ts-nocheck is intentional
    'src/types/database.ts',
  ]),
])

export default eslintConfig
