packages:
  - '.'
  - 'chrome-extension'

allowBuilds:
  sharp: false
  supabase: true
  unrs-resolver: false
  protobufjs: false
  '@sentry/cli': false
  '@ffmpeg-installer/darwin-arm64': true
  '@ffmpeg-installer/ffmpeg': true
  '@ffmpeg-installer/linux-x64': true
  '@ffmpeg-installer/linux-arm64': true
  '@ffprobe-installer/ffprobe': true
  '@ffprobe-installer/darwin-arm64': true
  '@ffprobe-installer/linux-x64': true
  '@ffprobe-installer/linux-arm64': true
