// reason: generated by `pnpm db:types` from the local Supabase schema. Do
// not hand-edit. Regenerate after every migration to keep client typings
// in sync with the database.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      activities: {
        Row: {
          actor_user_id: string | null
          body: string | null
          created_at: string
          entity_id: string
          entity_type: string
          id: string
          kind: Database["public"]["Enums"]["activity_kind"]
          metadata: Json
          occurred_at: string
          organization_id: string
        }
        Insert: {
          actor_user_id?: string | null
          body?: string | null
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
          kind: Database["public"]["Enums"]["activity_kind"]
          metadata?: Json
          occurred_at?: string
          organization_id: string
        }
        Update: {
          actor_user_id?: string | null
          body?: string | null
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          kind?: Database["public"]["Enums"]["activity_kind"]
          metadata?: Json
          occurred_at?: string
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "activities_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_usage: {
        Row: {
          cost_pence: number
          created_at: string
          id: string
          input_tokens: number
          latency_ms: number | null
          model: string
          organization_id: string
          output_tokens: number
          purpose: string
          user_id: string | null
        }
        Insert: {
          cost_pence: number
          created_at?: string
          id?: string
          input_tokens: number
          latency_ms?: number | null
          model: string
          organization_id: string
          output_tokens: number
          purpose: string
          user_id?: string | null
        }
        Update: {
          cost_pence?: number
          created_at?: string
          id?: string
          input_tokens?: number
          latency_ms?: number | null
          model?: string
          organization_id?: string
          output_tokens?: number
          purpose?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      applications: {
        Row: {
          application_type: Database["public"]["Enums"]["application_type"]
          candidate_id: string
          created_at: string
          created_by: string | null
          decline_notes: string | null
          decline_reason: Database["public"]["Enums"]["decline_reason"] | null
          declined_at: string | null
          id: string
          job_id: string
          organization_id: string
          owner_user_id: string | null
          stage: Database["public"]["Enums"]["application_stage"]
          stage_changed_at: string
          updated_at: string
        }
        Insert: {
          application_type?: Database["public"]["Enums"]["application_type"]
          candidate_id: string
          created_at?: string
          created_by?: string | null
          decline_notes?: string | null
          decline_reason?: Database["public"]["Enums"]["decline_reason"] | null
          declined_at?: string | null
          id?: string
          job_id: string
          organization_id: string
          owner_user_id?: string | null
          stage?: Database["public"]["Enums"]["application_stage"]
          stage_changed_at?: string
          updated_at?: string
        }
        Update: {
          application_type?: Database["public"]["Enums"]["application_type"]
          candidate_id?: string
          created_at?: string
          created_by?: string | null
          decline_notes?: string | null
          decline_reason?: Database["public"]["Enums"]["decline_reason"] | null
          declined_at?: string | null
          id?: string
          job_id?: string
          organization_id?: string
          owner_user_id?: string | null
          stage?: Database["public"]["Enums"]["application_stage"]
          stage_changed_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "applications_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: Database["public"]["Enums"]["audit_action"]
          actor_user_id: string | null
          at: string
          entity_id: string
          entity_type: string
          id: string
          metadata: Json
          organization_id: string
        }
        Insert: {
          action: Database["public"]["Enums"]["audit_action"]
          actor_user_id?: string | null
          at?: string
          entity_id: string
          entity_type: string
          id?: string
          metadata?: Json
          organization_id: string
        }
        Update: {
          action?: Database["public"]["Enums"]["audit_action"]
          actor_user_id?: string | null
          at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          metadata?: Json
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_log_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      candidate_cvs: {
        Row: {
          candidate_id: string
          created_at: string
          extracted_data: Json | null
          file_size_bytes: number | null
          id: string
          mime_type: string
          organization_id: string
          parse_error: string | null
          parsing_status: Database["public"]["Enums"]["cv_parsing_status"]
          storage_path: string
          updated_at: string
          uploaded_by: string | null
          version: number
        }
        Insert: {
          candidate_id: string
          created_at?: string
          extracted_data?: Json | null
          file_size_bytes?: number | null
          id?: string
          mime_type: string
          organization_id: string
          parse_error?: string | null
          parsing_status?: Database["public"]["Enums"]["cv_parsing_status"]
          storage_path: string
          updated_at?: string
          uploaded_by?: string | null
          version: number
        }
        Update: {
          candidate_id?: string
          created_at?: string
          extracted_data?: Json | null
          file_size_bytes?: number | null
          id?: string
          mime_type?: string
          organization_id?: string
          parse_error?: string | null
          parsing_status?: Database["public"]["Enums"]["cv_parsing_status"]
          storage_path?: string
          updated_at?: string
          uploaded_by?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "candidate_cvs_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidate_cvs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidate_cvs_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      candidates: {
        Row: {
          candidate_embedding: unknown
          consent_at: string | null
          consent_basis: Database["public"]["Enums"]["consent_basis"] | null
          consent_text_version: string | null
          created_at: string
          created_by: string | null
          currency: string
          current_company: string | null
          current_role_title: string | null
          email: string | null
          embedded_at: string | null
          embedding_version: number | null
          full_name: string
          id: string
          location: string | null
          market_status: Database["public"]["Enums"]["market_status"]
          market_status_at: string
          organization_id: string
          phone: string | null
          referrer_candidate_id: string | null
          salary_current_estimate: number | null
          salary_expectation: number | null
          sector_tags: string[]
          seniority_level: string | null
          skills: string[]
          source: Database["public"]["Enums"]["candidate_source"]
          source_detail: string | null
          updated_at: string
          years_experience: number | null
        }
        Insert: {
          candidate_embedding?: unknown
          consent_at?: string | null
          consent_basis?: Database["public"]["Enums"]["consent_basis"] | null
          consent_text_version?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string
          current_company?: string | null
          current_role_title?: string | null
          email?: string | null
          embedded_at?: string | null
          embedding_version?: number | null
          full_name: string
          id?: string
          location?: string | null
          market_status?: Database["public"]["Enums"]["market_status"]
          market_status_at?: string
          organization_id: string
          phone?: string | null
          referrer_candidate_id?: string | null
          salary_current_estimate?: number | null
          salary_expectation?: number | null
          sector_tags?: string[]
          seniority_level?: string | null
          skills?: string[]
          source?: Database["public"]["Enums"]["candidate_source"]
          source_detail?: string | null
          updated_at?: string
          years_experience?: number | null
        }
        Update: {
          candidate_embedding?: unknown
          consent_at?: string | null
          consent_basis?: Database["public"]["Enums"]["consent_basis"] | null
          consent_text_version?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string
          current_company?: string | null
          current_role_title?: string | null
          email?: string | null
          embedded_at?: string | null
          embedding_version?: number | null
          full_name?: string
          id?: string
          location?: string | null
          market_status?: Database["public"]["Enums"]["market_status"]
          market_status_at?: string
          organization_id?: string
          phone?: string | null
          referrer_candidate_id?: string | null
          salary_current_estimate?: number | null
          salary_expectation?: number | null
          sector_tags?: string[]
          seniority_level?: string | null
          skills?: string[]
          source?: Database["public"]["Enums"]["candidate_source"]
          source_detail?: string | null
          updated_at?: string
          years_experience?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "candidates_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidates_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidates_referrer_candidate_id_fkey"
            columns: ["referrer_candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          industry: string | null
          last_contacted_at: string | null
          name: string
          notes: string | null
          organization_id: string
          updated_at: string
          website: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          industry?: string | null
          last_contacted_at?: string | null
          name: string
          notes?: string | null
          organization_id: string
          updated_at?: string
          website?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          industry?: string | null
          last_contacted_at?: string | null
          name?: string
          notes?: string | null
          organization_id?: string
          updated_at?: string
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "companies_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "companies_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          company_id: string
          created_at: string
          created_by: string | null
          email: string | null
          full_name: string
          id: string
          last_contacted_at: string | null
          notes: string | null
          organization_id: string
          phone: string | null
          role_title: string | null
          updated_at: string
        }
        Insert: {
          company_id: string
          created_at?: string
          created_by?: string | null
          email?: string | null
          full_name: string
          id?: string
          last_contacted_at?: string | null
          notes?: string | null
          organization_id: string
          phone?: string | null
          role_title?: string | null
          updated_at?: string
        }
        Update: {
          company_id?: string
          created_at?: string
          created_by?: string | null
          email?: string | null
          full_name?: string
          id?: string
          last_contacted_at?: string | null
          notes?: string | null
          organization_id?: string
          phone?: string | null
          role_title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contacts_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contacts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          company_id: string
          created_at: string
          created_by: string | null
          currency: string
          day_rate_max: number | null
          day_rate_min: number | null
          description: string | null
          embedded_at: string | null
          embedding_version: number | null
          fee_percent: number | null
          hiring_context: Database["public"]["Enums"]["hiring_context"]
          id: string
          job_embedding: unknown
          job_type: Database["public"]["Enums"]["job_type"]
          location: string | null
          organization_id: string
          owner_user_id: string | null
          salary_max: number | null
          salary_min: number | null
          status: Database["public"]["Enums"]["job_status"]
          title: string
          updated_at: string
        }
        Insert: {
          company_id: string
          created_at?: string
          created_by?: string | null
          currency?: string
          day_rate_max?: number | null
          day_rate_min?: number | null
          description?: string | null
          embedded_at?: string | null
          embedding_version?: number | null
          fee_percent?: number | null
          hiring_context?: Database["public"]["Enums"]["hiring_context"]
          id?: string
          job_embedding?: unknown
          job_type?: Database["public"]["Enums"]["job_type"]
          location?: string | null
          organization_id: string
          owner_user_id?: string | null
          salary_max?: number | null
          salary_min?: number | null
          status?: Database["public"]["Enums"]["job_status"]
          title: string
          updated_at?: string
        }
        Update: {
          company_id?: string
          created_at?: string
          created_by?: string | null
          currency?: string
          day_rate_max?: number | null
          day_rate_min?: number | null
          description?: string | null
          embedded_at?: string | null
          embedding_version?: number | null
          fee_percent?: number | null
          hiring_context?: Database["public"]["Enums"]["hiring_context"]
          id?: string
          job_embedding?: unknown
          job_type?: Database["public"]["Enums"]["job_type"]
          location?: string | null
          organization_id?: string
          owner_user_id?: string | null
          salary_max?: number | null
          salary_min?: number | null
          status?: Database["public"]["Enums"]["job_status"]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          created_at: string
          email: string
          full_name: string | null
          id: string
          organization_id: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          organization_id: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          organization_id?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_organization_id: { Args: never; Returns: string }
      record_ai_usage: {
        Args: {
          p_cost_pence: number
          p_input_tokens: number
          p_latency_ms?: number
          p_model: string
          p_organization_id: string
          p_output_tokens: number
          p_purpose: string
          p_user_id?: string
        }
        Returns: string
      }
      record_audit: {
        Args: {
          p_action: Database["public"]["Enums"]["audit_action"]
          p_entity_id: string
          p_entity_type: string
          p_metadata?: Json
        }
        Returns: string
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      activity_kind:
        | "note"
        | "call"
        | "email"
        | "meeting"
        | "stage_change"
        | "system"
      application_stage:
        | "applied"
        | "screening"
        | "cv_submitted"
        | "first_interview"
        | "second_interview"
        | "offer"
        | "placed"
        | "rejected"
        | "withdrawn"
      application_type: "standard" | "spec" | "float"
      audit_action: "view" | "create" | "update" | "delete" | "export"
      candidate_source:
        | "apply_form"
        | "linkedin"
        | "referral"
        | "email_inbox"
        | "event"
        | "direct_add"
        | "other"
      consent_basis: "consent" | "legitimate_interest"
      cv_parsing_status: "pending" | "complete" | "failed"
      decline_reason:
        | "not_qualified"
        | "salary_mismatch"
        | "location_mismatch"
        | "candidate_withdrew"
        | "client_rejected_skills"
        | "client_rejected_culture"
        | "client_filled_internally"
        | "client_filled_other"
        | "other"
      hiring_context: "new_role" | "backfill"
      job_status: "draft" | "open" | "on_hold" | "filled" | "cancelled"
      job_type: "perm" | "contract" | "temp"
      market_status:
        | "actively_looking"
        | "passively_looking"
        | "hot"
        | "placed"
        | "cold"
      user_role: "owner" | "admin" | "recruiter"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      activity_kind: [
        "note",
        "call",
        "email",
        "meeting",
        "stage_change",
        "system",
      ],
      application_stage: [
        "applied",
        "screening",
        "cv_submitted",
        "first_interview",
        "second_interview",
        "offer",
        "placed",
        "rejected",
        "withdrawn",
      ],
      application_type: ["standard", "spec", "float"],
      audit_action: ["view", "create", "update", "delete", "export"],
      candidate_source: [
        "apply_form",
        "linkedin",
        "referral",
        "email_inbox",
        "event",
        "direct_add",
        "other",
      ],
      consent_basis: ["consent", "legitimate_interest"],
      cv_parsing_status: ["pending", "complete", "failed"],
      decline_reason: [
        "not_qualified",
        "salary_mismatch",
        "location_mismatch",
        "candidate_withdrew",
        "client_rejected_skills",
        "client_rejected_culture",
        "client_filled_internally",
        "client_filled_other",
        "other",
      ],
      hiring_context: ["new_role", "backfill"],
      job_status: ["draft", "open", "on_hold", "filled", "cancelled"],
      job_type: ["perm", "contract", "temp"],
      market_status: [
        "actively_looking",
        "passively_looking",
        "hot",
        "placed",
        "cold",
      ],
      user_role: ["owner", "admin", "recruiter"],
    },
  },
} as const
