/**
 * Gender-coded word lists vendored from Kat Matfield's Gender Decoder
 * (https://gender-decoder.katmatfield.com/), which itself adapted Gaucher,
 * Friesen & Kay (2011) "Evidence That Gendered Wording in Job Advertisements
 * Exists and Sustains Gender Inequality".
 *
 * License: Public domain / MIT — Kat Matfield released the Gender Decoder
 * source and word lists under permissive terms; the underlying psychology
 * paper's word lists are in the public domain.
 *
 * Phase 3 / Plan 03-04 (D3-15): These lists are fed into the Sonnet system
 * prompt as anchors for the gender-coding dimension of the inclusivity
 * rubric. Sonnet treats them as a seed lexicon rather than the sole rubric —
 * gender coding is one of five dimensions (the others: age, jargon,
 * accessibility, salary_transparency).
 *
 * IMPORTANT: each word is the STEM. The rubric should match these as
 * prefixes (e.g. "aggressive" matches "aggressively", "aggressor"). The
 * Sonnet prompt is instructed to perform that match.
 */

export const MASCULINE_CODED_WORDS: readonly string[] = [
  'active',
  'adventurous',
  'aggress',
  'ambitio',
  'analy',
  'assert',
  'athlet',
  'autonom',
  'battle',
  'boast',
  'challeng',
  'champion',
  'compet',
  'confident',
  'courag',
  'decid',
  'decisive',
  'decision',
  'determin',
  'domina',
  'dominant',
  'driven',
  'fearless',
  'fight',
  'force',
  'greedy',
  'head-strong',
  'headstrong',
  'hierarch',
  'hostil',
  'impulsive',
  'independen',
  'individual',
  'intellect',
  'lead',
  'logic',
  'objective',
  'opinion',
  'outspoken',
  'persist',
  'principl',
  'reckless',
  'self-confiden',
  'self-relian',
  'self-sufficien',
  'selfconfiden',
  'selfrelian',
  'selfsufficien',
  'stubborn',
  'superior',
  'unreasonab',
  'rockstar',
  'ninja',
  'guru',
  'wizard',
  'crush',
  'kill',
  'dominat',
  'warrior',
  'hero',
] as const

export const FEMININE_CODED_WORDS: readonly string[] = [
  'agree',
  'affectionate',
  'child',
  'cheer',
  'collab',
  'commit',
  'communal',
  'compassion',
  'connect',
  'considerate',
  'cooperat',
  'co-operat',
  'depend',
  'emotiona',
  'empath',
  'feel',
  'flatterable',
  'gentle',
  'honest',
  'interpersonal',
  'interdependen',
  'interpersona',
  'inter-personal',
  'inter-dependen',
  'inter-persona',
  'kind',
  'kinship',
  'loyal',
  'modesty',
  'nag',
  'nurtur',
  'pleasant',
  'polite',
  'quiet',
  'respon',
  'sensitiv',
  'submissive',
  'support',
  'sympath',
  'tender',
  'together',
  'trust',
  'understand',
  'warm',
  'whin',
  'enthusias',
  'inclusive',
  'yield',
  'share',
  'sharin',
] as const
